### ISSUE TITLE
How to install? What dependencies are required?

### ISSUE THREAD

**Issue by huameiwei-vc** [GeekyGhost/ComfyUI-GeekyRemB#1]
I can't find the node after git clone installation

**Comment by GeekyGhost** [comment]
My apologies, added requirements.txt. pip install requirements.txt I'll set it up like a node package to make it easier. Most requirements are likely installed already. I tried to stick with commonly used libraries. There's some wild ones out there lol, and some with un fun licenses lol. So, I went simple.

**Comment by huameiwei-vc** [comment]
Thanks, but after my experimental install, it still doesn't show the nodes, and I'm sure I've installed the dependencies. pip install -r requirements.txt

**Comment by GeekyGhost** [comment]
> Thanks, but after my experimental install, it still doesn't show the nodes, and I'm sure I've installed the dependencies. pip install -r requirements.txt

let me do a proper package for comfyUI and that should sort it. That way comfy installs the dependencies. Give me a day or two, just finished my video for the contest so I can update my workflows and code bases again.

**Comment by cian0** [comment]
> > Thanks, but after my experimental install, it still doesn't show the nodes, and I'm sure I've installed the dependencies. pip install -r requirements.txt
> 
> let me do a proper package for comfyUI and that should sort it. That way comfy installs the dependencies. Give me a day or two, just finished my video for the contest so I can update my workflows and code bases again.

`Traceback (most recent call last):
  File "/app/nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/app/custom_nodes/ComfyUI-GeekyRemB/__init__.py'

`

I also couldn't load the library, for your reference, thanks and good luck with the contest! :)

**Comment by GeekyGhost** [comment]
> > > Thanks, but after my experimental install, it still doesn't show the nodes, and I'm sure I've installed the dependencies. pip install -r requirements.txt
> > 
> > 
> > let me do a proper package for comfyUI and that should sort it. That way comfy installs the dependencies. Give me a day or two, just finished my video for the contest so I can update my workflows and code bases again.
> 
> `Traceback (most recent call last): File "/app/nodes.py", line 1931, in load_custom_node module_spec.loader.exec_module(module) File "", line 879, in exec_module File "", line 1016, in get_code File "", line 1073, in get_data FileNotFoundError: [Errno 2] No such file or directory: '/app/custom_nodes/ComfyUI-GeekyRemB/**init**.py'
> 
> `
> 
> I also couldn't load the library, for your reference, thanks and good luck with the contest! :)

give it a go now?
