### ISSUE TITLE
?what is this

### ISSUE THREAD

**Issue by 4lt3r3go** [GeekyGhost/ComfyUI-GeekyRemB#5]
during install i got this:

`Username for 'https://github.com':`

is asking for credential

never saw this in more than a year of comfy usage

**Comment by GeekyGhost** [comment]
Can you share how exactly you're trying to install this node? That would help me provide more specific guidance. 

The prompt for GitHub credentials you've seen (Username for 'https://github.com':) typically appears when you try to access a private repository or your local Git configuration settings have changed.

**Comment by 4lt3r3go** [comment]
git clone, as written in the install instruction of this page

**Comment by 4lt3r3go** [comment]
my bad, i havent noticed the "your user name" was in the link. i swapped with the page link and worked. sorry
