### ISSUE TITLE
how can i solve this? please help🙏🏻

### ISSUE THREAD

**Issue by 4lt3r3go** [GeekyGhost/ComfyUI-GeekyRemB#6]
`Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!`

i'm trying all the background removal around and always getting this error.
is so frustrating

**Comment by GeekyGhost** [comment]
It sounds like you're facing an issue with your CUDA and cuDNN setup, specifically with the missing cudnn_ops_infer64_8.dll file. This error occurs when TensorFlow or PyTorch is unable to locate the cuDNN (CUDA Deep Neural Network) library that’s required for GPU acceleration.
